stages:
  - build
  - test
  - push_to_dockerhub
  - deploy

build_job:
  stage: build
  script:
    - docker build -t currency-converter-app:latest .
  tags:
    - dev

test_job:
  stage: test
  script:
    - echo "testing ...."
  tags:
    - dev

push_job:
  stage: push_to_dockerhub
  script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
    - docker tag currency-converter-app:latest $DOCKERHUB_USER/currency-converter-app:latest
    - docker push $DOCKERHUB_USER/currency-converter-app:latest
  tags:
    - dev

deploy_job:
  stage: deploy
  script:
    - docker-compose up -d
  tags:
    - dev
